### ISSUE TITLE
close this repo?

### ISSUE THREAD

**Issue by tobiasbueschel** [Web-VR/awesome-webvr#1]
Hi @cvan :wave:

really appreciate your efforts, but I saw that there is already a well-maintained `awesome-webvr` list: https://github.com/wizztjh/awesome-WebVR

Perhaps we can close this list here?

Cheers
cc @wizztjh

**Comment by wizztjh** [comment]
Hey @cvan, i can transfer the repo to you if you want to consolidate it to webvr

**Comment by cvan** [comment]
I'll close this down, yeah - thanks for reminding me
